// Science database for the "Let's Learn" Module
// Class 6–8 educational details for 50 metals and 50 non-metals/compounds.

export const metalsData = [
  {
    id: 'lithium',
    name: 'Lithium',
    symbol: 'Li',
    atomicNumber: 3,
    category: 'Alkali Metal',
    uses: 'Rechargeable batteries for phones and laptops, psychiatric medicine.',
    fact: 'It is the lightest of all metals and can easily float on water!',
    color: '#38BDF8',
    shellConfig: [2, 1]
  },
  {
    id: 'sodium',
    name: 'Sodium',
    symbol: 'Na',
    atomicNumber: 11,
    category: 'Alkali Metal',
    uses: 'Streetlights (yellow vapour lamps), heat transfers, table salt component.',
    fact: 'Sodium is so soft you can easily cut it with a butter knife!',
    color: '#0ea5e9',
    shellConfig: [2, 8, 1]
  },
  {
    id: 'potassium',
    name: 'Potassium',
    symbol: 'K',
    atomicNumber: 19,
    category: 'Alkali Metal',
    uses: 'Fertilizers, soap manufacturing, cellular function in human body.',
    fact: 'Potassium reacts explosively when it touches water, producing purple flames!',
    color: '#0284c7',
    shellConfig: [2, 8, 8, 1]
  },
  {
    id: 'rubidium',
    name: 'Rubidium',
    symbol: 'Rb',
    atomicNumber: 37,
    category: 'Alkali Metal',
    uses: 'Atomic clocks, fireworks (purple color), photocells.',
    fact: 'Rubidium melts at just 39.3°C, which is close to human body temperature!',
    color: '#0369a1',
    shellConfig: [2, 8, 18, 8, 1]
  },
  {
    id: 'caesium',
    name: 'Caesium',
    symbol: 'Cs',
    atomicNumber: 55,
    category: 'Alkali Metal',
    uses: 'Defining the standard second in atomic clocks, drilling fluids.',
    fact: 'Caesium is the most reactive metal on Earth and melts in a warm room!',
    color: '#075985',
    shellConfig: [2, 8, 18, 18, 8, 1]
  },
  {
    id: 'beryllium',
    name: 'Beryllium',
    symbol: 'Be',
    atomicNumber: 4,
    category: 'Alkaline Earth',
    uses: 'Aerospace structural materials, x-ray tube windows, mirrors.',
    fact: 'Beryllium is sweet to taste, but is highly toxic to humans!',
    color: '#34D399',
    shellConfig: [2, 2]
  },
  {
    id: 'magnesium',
    name: 'Magnesium',
    symbol: 'Mg',
    atomicNumber: 12,
    category: 'Alkaline Earth',
    uses: 'Flares, fireworks, lightweight alloys for laptop bodies and cars.',
    fact: 'Magnesium burns with an incredibly bright, blinding white light!',
    color: '#10B981',
    shellConfig: [2, 8, 2]
  },
  {
    id: 'calcium',
    name: 'Calcium',
    symbol: 'Ca',
    atomicNumber: 20,
    category: 'Alkaline Earth',
    uses: 'Cement, plaster, steel refining, nutritional supplements.',
    fact: 'Calcium is the 5th most abundant element in the human body, key to bones and teeth!',
    color: '#059669',
    shellConfig: [2, 8, 8, 2]
  },
  {
    id: 'strontium',
    name: 'Strontium',
    symbol: 'Sr',
    atomicNumber: 38,
    category: 'Alkaline Earth',
    uses: 'Red fireworks, glow-in-the-dark paints, magnets.',
    fact: 'Strontium salts are what give fireworks their brilliant deep red color!',
    color: '#047857',
    shellConfig: [2, 8, 18, 8, 2]
  },
  {
    id: 'barium',
    name: 'Barium',
    symbol: 'Ba',
    atomicNumber: 56,
    category: 'Alkaline Earth',
    uses: 'Medical imaging (barium swallow), green fireworks, glass manufacturing.',
    fact: 'It is highly reactive and oxidizes in air almost immediately!',
    color: '#065f46',
    shellConfig: [2, 8, 18, 18, 8, 2]
  },
  {
    id: 'radium',
    name: 'Radium',
    symbol: 'Ra',
    atomicNumber: 88,
    category: 'Alkaline Earth',
    uses: 'Historically used in self-luminous watch dials, cancer treatments.',
    fact: 'Radium glows in the dark because of its intense radioactivity!',
    color: '#064e3b',
    shellConfig: [2, 8, 18, 32, 18, 8, 2]
  },
  {
    id: 'scandium',
    name: 'Scandium',
    symbol: 'Sc',
    atomicNumber: 21,
    category: 'Transition Metal',
    uses: 'Bicycle frames, baseball bats, aerospace components.',
    fact: 'It was discovered in Scandinavia and is surprisingly lightweight!',
    color: '#a78bfa',
    shellConfig: [2, 8, 9, 2]
  },
  {
    id: 'titanium',
    name: 'Titanium',
    symbol: 'Ti',
    atomicNumber: 22,
    category: 'Transition Metal',
    uses: 'Spacecraft, medical implants (joints, dental), fighter jets.',
    fact: 'Titanium is as strong as steel but 45% lighter, and it never rusts!',
    color: '#8B5CF6',
    shellConfig: [2, 8, 10, 2]
  },
  {
    id: 'vanadium',
    name: 'Vanadium',
    symbol: 'V',
    atomicNumber: 23,
    category: 'Transition Metal',
    uses: 'Rust-resistant high-speed steel alloys, tools, car parts.',
    fact: 'Adding a tiny bit of Vanadium to steel makes it extremely tough!',
    color: '#7C3AED',
    shellConfig: [2, 8, 11, 2]
  },
  {
    id: 'chromium',
    name: 'Chromium',
    symbol: 'Cr',
    atomicNumber: 24,
    category: 'Transition Metal',
    uses: 'Chrome plating, stainless steel (anti-rust), pigment dye.',
    fact: 'Chromium gives rubies their beautiful red color and emeralds their green!',
    color: '#6D28D9',
    shellConfig: [2, 8, 13, 1]
  },
  {
    id: 'manganese',
    name: 'Manganese',
    symbol: 'Mn',
    atomicNumber: 25,
    category: 'Transition Metal',
    uses: 'Steel alloy production, alkaline batteries, aluminum beverage cans.',
    fact: 'Without Manganese, steel would shatter when struck with a hammer!',
    color: '#5B21B6',
    shellConfig: [2, 8, 13, 2]
  },
  {
    id: 'iron',
    name: 'Iron',
    symbol: 'Fe',
    atomicNumber: 26,
    category: 'Transition Metal',
    uses: 'Building bridges, vehicles, machinery, red blood cell hemoglobin.',
    fact: 'Iron makes up most of Earth\'s core and was used to make ancient swords!',
    color: '#4C1D95',
    shellConfig: [2, 8, 14, 2]
  },
  {
    id: 'cobalt',
    name: 'Cobalt',
    symbol: 'Co',
    atomicNumber: 27,
    category: 'Transition Metal',
    uses: 'Rechargeable batteries, blue pigments (cobalt blue), jet turbines.',
    fact: 'Cobalt gets its name from "kobold", German for goblin, due to tricky ores!',
    color: '#2563EB',
    shellConfig: [2, 8, 15, 2]
  },
  {
    id: 'nickel',
    name: 'Nickel',
    symbol: 'Ni',
    atomicNumber: 28,
    category: 'Transition Metal',
    uses: 'Coins, guitar strings, stainless steel, rechargeable batteries.',
    fact: 'Most of Earth\'s meteorites are alloys of iron and nickel!',
    color: '#3B82F6',
    shellConfig: [2, 8, 16, 2]
  },
  {
    id: 'copper',
    name: 'Copper',
    symbol: 'Cu',
    atomicNumber: 29,
    category: 'Transition Metal',
    uses: 'Electrical wires, water pipes, kitchen utensils, coins.',
    fact: 'Copper is naturally antibacterial; germs die rapidly on its surface!',
    color: '#F97316',
    shellConfig: [2, 8, 18, 1]
  },
  {
    id: 'zinc',
    name: 'Zinc',
    symbol: 'Zn',
    atomicNumber: 30,
    category: 'Transition Metal',
    uses: 'Galvanizing iron (preventing rust), sunscreen, brass alloys.',
    fact: 'Zinc is an essential mineral that helps your immune system fight off colds!',
    color: '#10B981',
    shellConfig: [2, 8, 18, 2]
  },
  {
    id: 'yttrium',
    name: 'Yttrium',
    symbol: 'Y',
    atomicNumber: 39,
    category: 'Transition Metal',
    uses: 'LED lights, lasers, camera lenses, superconductors.',
    fact: 'Moon rocks collected during the Apollo missions contain high levels of Yttrium!',
    color: '#14B8A6',
    shellConfig: [2, 8, 18, 9, 2]
  },
  {
    id: 'zirconium',
    name: 'Zirconium',
    symbol: 'Zr',
    atomicNumber: 40,
    category: 'Transition Metal',
    uses: 'Nuclear reactor cladding, artificial diamonds (cubic zirconia).',
    fact: 'Zirconium is highly resistant to heat, acids, and corrosion!',
    color: '#0D9488',
    shellConfig: [2, 8, 18, 10, 2]
  },
  {
    id: 'niobium',
    name: 'Niobium',
    symbol: 'Nb',
    atomicNumber: 41,
    category: 'Transition Metal',
    uses: 'Superconducting magnets in MRI machines, particle accelerators.',
    fact: 'Niobium can be anodized to create beautiful metallic rainbow colors!',
    color: '#0F766E',
    shellConfig: [2, 8, 18, 12, 1]
  },
  {
    id: 'molybdenum',
    name: 'Molybdenum',
    symbol: 'Mo',
    atomicNumber: 42,
    category: 'Transition Metal',
    uses: 'High-strength steel, aircraft parts, industrial lubricants.',
    fact: 'It has one of the highest melting points of all elements (2,623°C)!',
    color: '#115E59',
    shellConfig: [2, 8, 18, 13, 1]
  },
  {
    id: 'ruthenium',
    name: 'Ruthenium',
    symbol: 'Ru',
    atomicNumber: 44,
    category: 'Transition Metal',
    uses: 'Electrical contacts, wear-resistant alloys, chemical catalysts.',
    fact: 'It is a rare transition metal that belongs to the platinum group!',
    color: '#F43F5E',
    shellConfig: [2, 8, 18, 15, 1]
  },
  {
    id: 'rhodium',
    name: 'Rhodium',
    symbol: 'Rh',
    atomicNumber: 45,
    category: 'Transition Metal',
    uses: 'Catalytic converters in cars, plating white gold jewelry.',
    fact: 'Rhodium is one of the rarest and most expensive metals in the world!',
    color: '#E11D48',
    shellConfig: [2, 8, 18, 16, 1]
  },
  {
    id: 'palladium',
    name: 'Palladium',
    symbol: 'Pd',
    atomicNumber: 46,
    category: 'Transition Metal',
    uses: 'Hydrogen purification, catalytic converters, electronics.',
    fact: 'Palladium can absorb up to 900 times its own volume of hydrogen gas!',
    color: '#BE123C',
    shellConfig: [2, 8, 18, 18]
  },
  {
    id: 'silver',
    name: 'Silver',
    symbol: 'Ag',
    atomicNumber: 47,
    category: 'Transition Metal',
    uses: 'Jewelry, mirrors, high-end electronics, silver-oxide batteries.',
    fact: 'Silver has the highest electrical and thermal conductivity of any metal!',
    color: '#94A3B8',
    shellConfig: [2, 8, 18, 18, 1]
  },
  {
    id: 'cadmium',
    name: 'Cadmium',
    symbol: 'Cd',
    atomicNumber: 48,
    category: 'Transition Metal',
    uses: 'Rechargeable Ni-Cd batteries, yellow pigments, nuclear control rods.',
    fact: 'Cadmium is toxic and is being phased out in favour of safer metals!',
    color: '#64748B',
    shellConfig: [2, 8, 18, 18, 2]
  },
  {
    id: 'hafnium',
    name: 'Hafnium',
    symbol: 'Hf',
    atomicNumber: 72,
    category: 'Transition Metal',
    uses: 'Nuclear control rods, computer microprocessors, superalloys.',
    fact: 'Hafnium absorbs neutrons extremely well, helping control nuclear reactors!',
    color: '#475569',
    shellConfig: [2, 8, 18, 32, 10, 2]
  },
  {
    id: 'tantalum',
    name: 'Tantalum',
    symbol: 'Ta',
    atomicNumber: 73,
    category: 'Transition Metal',
    uses: 'Capacitors in smartphones, surgical implants, jet engines.',
    fact: 'Tantalum is completely immune to body fluids, making it perfect for bone repairs!',
    color: '#334155',
    shellConfig: [2, 8, 18, 32, 11, 2]
  },
  {
    id: 'tungsten',
    name: 'Tungsten',
    symbol: 'W',
    atomicNumber: 74,
    category: 'Transition Metal',
    uses: 'Lightbulb filaments, cutting tools, armor-piercing ammunition.',
    fact: 'Tungsten has the highest melting point of all metals: 3,422°C!',
    color: '#1E293B',
    shellConfig: [2, 8, 18, 32, 12, 2]
  },
  {
    id: 'rhenium',
    name: 'Rhenium',
    symbol: 'Re',
    atomicNumber: 75,
    category: 'Transition Metal',
    uses: 'Nickel-based superalloys for jet engines, catalysts.',
    fact: 'Rhenium was the last naturally occurring, stable element to be discovered (1925)!',
    color: '#84CC16',
    shellConfig: [2, 8, 18, 32, 13, 2]
  },
  {
    id: 'osmium',
    name: 'Osmium',
    symbol: 'Os',
    atomicNumber: 76,
    category: 'Transition Metal',
    uses: 'Fountain pen tips, electrical contacts, wear-resistant pivots.',
    fact: 'Osmium is the densest naturally occurring element on Earth!',
    color: '#65A30D',
    shellConfig: [2, 8, 18, 32, 14, 2]
  },
  {
    id: 'iridium',
    name: 'Iridium',
    symbol: 'Ir',
    atomicNumber: 77,
    category: 'Transition Metal',
    uses: 'Spark plugs, crucibles for high-temp melting, compass pivots.',
    fact: 'A layer of iridium in Earth\'s crust supports the asteroid extinction theory!',
    color: '#4D7C0F',
    shellConfig: [2, 8, 18, 32, 15, 2]
  },
  {
    id: 'platinum',
    name: 'Platinum',
    symbol: 'Pt',
    atomicNumber: 78,
    category: 'Transition Metal',
    uses: 'Jewelry, catalytic converters, chemotherapy drugs, laboratory ware.',
    fact: 'It is so unreactive that it does not oxidize in air at any temperature!',
    color: '#CBD5E1',
    shellConfig: [2, 8, 18, 32, 17, 1]
  },
  {
    id: 'gold',
    name: 'Gold',
    symbol: 'Au',
    atomicNumber: 79,
    category: 'Transition Metal',
    uses: 'Jewelry, currency backing, computer chips, dental fillings.',
    fact: 'Gold is incredibly malleable; one ounce can be hammered into a 300 sq ft sheet!',
    color: '#EAB308',
    shellConfig: [2, 8, 18, 32, 18, 1]
  },
  {
    id: 'mercury',
    name: 'Mercury',
    symbol: 'Hg',
    atomicNumber: 80,
    category: 'Transition Metal',
    uses: 'Thermometers, barometers, fluorescent lighting, dental amalgams.',
    fact: 'Mercury is the only metal that is liquid at standard room temperature!',
    color: '#94A3B8',
    shellConfig: [2, 8, 18, 32, 18, 2]
  },
  {
    id: 'aluminium',
    name: 'Aluminium',
    symbol: 'Al',
    atomicNumber: 13,
    category: 'Post-Transition',
    uses: 'Soda cans, foil wrap, airplane fuselages, window frames.',
    fact: 'Aluminium is the most abundant metal in the Earth\'s crust!',
    color: '#A1A1AA',
    shellConfig: [2, 8, 3]
  },
  {
    id: 'gallium',
    name: 'Gallium',
    symbol: 'Ga',
    atomicNumber: 31,
    category: 'Post-Transition',
    uses: 'Semiconductors, blue LEDs, high-temperature thermometers.',
    fact: 'Gallium melts at 29.76°C; it will literally melt in the palm of your hand!',
    color: '#71717A',
    shellConfig: [2, 8, 18, 3]
  },
  {
    id: 'indium',
    name: 'Indium',
    symbol: 'In',
    atomicNumber: 49,
    category: 'Post-Transition',
    uses: 'Touch screens (Indium Tin Oxide), liquid crystal displays, solder.',
    fact: 'When bent, pure indium metal emits a high-pitched "scream" sound!',
    color: '#52525B',
    shellConfig: [2, 8, 18, 18, 3]
  },
  {
    id: 'tin',
    name: 'Tin',
    symbol: 'Sn',
    atomicNumber: 50,
    category: 'Post-Transition',
    uses: 'Plating steel cans for food (tin cans), solder, bronze alloy component.',
    fact: 'Tin has been used by humans since the Bronze Age, starting around 3000 BC!',
    color: '#D1D5DB',
    shellConfig: [2, 8, 18, 18, 4]
  },
  {
    id: 'lead',
    name: 'Lead',
    symbol: 'Pb',
    atomicNumber: 82,
    category: 'Post-Transition',
    uses: 'Car batteries, radiation shields in hospitals, ammunition.',
    fact: 'Lead is extremely heavy and toxic, and was once used in house paints and pipes!',
    color: '#9CA3AF',
    shellConfig: [2, 8, 18, 32, 18, 4]
  },
  {
    id: 'bismuth',
    name: 'Bismuth',
    symbol: 'Bi',
    atomicNumber: 83,
    category: 'Post-Transition',
    uses: 'Stomach medicine (Pepto-Bismol), fire sprinklers, cosmetics.',
    fact: 'Bismuth crystals oxidize into stunning, iridescent rainbow stair-step structures!',
    color: '#E2E8F0',
    shellConfig: [2, 8, 18, 32, 18, 5]
  },
  {
    id: 'lanthanum',
    name: 'Lanthanum',
    symbol: 'La',
    atomicNumber: 57,
    category: 'Lanthanide',
    uses: 'Camera lenses (improves glass quality), battery electrodes, hybrid cars.',
    fact: 'Lanthanum is highly reactive and catches fire easily when scratched!',
    color: '#A7F3D0',
    shellConfig: [2, 8, 18, 18, 9, 2]
  },
  {
    id: 'cerium',
    name: 'Cerium',
    symbol: 'Ce',
    atomicNumber: 58,
    category: 'Lanthanide',
    uses: 'Lighter flints, catalytic converters, polishing glass.',
    fact: 'Cerium is the most abundant of the rare earth elements on Earth!',
    color: '#6EE7B7',
    shellConfig: [2, 8, 18, 19, 9, 2]
  },
  {
    id: 'uranium',
    name: 'Uranium',
    symbol: 'U',
    atomicNumber: 92,
    category: 'Actinide',
    uses: 'Nuclear power plants fuel, armor plating, naval propulsion.',
    fact: 'A single gram of Uranium contains as much energy as 3 tons of coal!',
    color: '#22C55E',
    shellConfig: [2, 8, 18, 32, 21, 9, 2]
  },
  {
    id: 'steel',
    name: 'Steel',
    symbol: 'Fe+C',
    atomicNumber: 0, // Alloy
    category: 'Alloy',
    uses: 'Skyscrapers, bridges, cars, cutlery, tools, nails.',
    fact: 'Steel is an alloy made of iron mixed with carbon, making it 1000x stronger than pure iron!',
    color: '#475569',
    shellConfig: null
  },
  {
    id: 'brass',
    name: 'Brass',
    symbol: 'Cu+Zn',
    atomicNumber: 0, // Alloy
    category: 'Alloy',
    uses: 'Musical instruments (trumpets, horns), door locks, decorative items.',
    fact: 'Brass has acoustic properties that make it vibrate beautifully when blown!',
    color: '#FBBF24',
    shellConfig: null
  }
];

export const nonMetalsData = [
  {
    id: 'hydrogen',
    name: 'Hydrogen',
    symbol: 'H',
    atomicNumber: 1,
    category: 'Reactive Nonmetal',
    uses: 'Rocket fuel, fertilizer production, clean energy fuel cells.',
    fact: 'Hydrogen is the most abundant element in the Universe, making up stars like our Sun!',
    color: '#F472B6',
    shellConfig: [1]
  },
  {
    id: 'carbon',
    name: 'Carbon',
    symbol: 'C',
    atomicNumber: 6,
    category: 'Reactive Nonmetal',
    uses: 'Pencils (graphite), fuel (coal), jewelry (diamond), organic chemistry base.',
    fact: 'All life on Earth is carbon-based! Diamond and pencil lead are made of pure carbon!',
    color: '#4B5563',
    shellConfig: [2, 4]
  },
  {
    id: 'nitrogen',
    name: 'Nitrogen',
    symbol: 'N',
    atomicNumber: 7,
    category: 'Reactive Nonmetal',
    uses: 'Food packaging (keeps chips fresh), fertilizers, liquid coolant.',
    fact: 'Over 78% of Earth\'s atmosphere is pure, breathable nitrogen gas!',
    color: '#60A5FA',
    shellConfig: [2, 5]
  },
  {
    id: 'oxygen',
    name: 'Oxygen',
    symbol: 'O',
    atomicNumber: 8,
    category: 'Reactive Nonmetal',
    uses: 'Respiration support in hospitals, steel manufacturing, water molecules.',
    fact: 'Liquid oxygen is pale blue and highly magnetic!',
    color: '#3B82F6',
    shellConfig: [2, 6]
  },
  {
    id: 'phosphorus',
    name: 'Phosphorus',
    symbol: 'P',
    atomicNumber: 15,
    category: 'Reactive Nonmetal',
    uses: 'Safety matchsticks, fertilizers, detergents, DNA structure.',
    fact: 'White phosphorus glows in the dark when exposed to oxygen!',
    color: '#F59E0B',
    shellConfig: [2, 8, 5]
  },
  {
    id: 'sulfur',
    name: 'Sulfur',
    symbol: 'S',
    atomicNumber: 16,
    category: 'Reactive Nonmetal',
    uses: 'Gunpowder, vulcanizing rubber, sulfuric acid, skin creams.',
    fact: 'Pure sulfur is bright yellow and has a strong smell like rotten eggs!',
    color: '#EAB308',
    shellConfig: [2, 8, 6]
  },
  {
    id: 'selenium',
    name: 'Selenium',
    symbol: 'Se',
    atomicNumber: 34,
    category: 'Reactive Nonmetal',
    uses: 'Photocopy machines, light meters, glass coloring, shampoo.',
    fact: 'Selenium is highly photoconductive; it conducts electricity much better in the light!',
    color: '#EC4899',
    shellConfig: [2, 8, 18, 6]
  },
  {
    id: 'fluorine',
    name: 'Fluorine',
    symbol: 'F',
    atomicNumber: 9,
    category: 'Halogen',
    uses: 'Toothpaste (sodium fluoride to prevent cavities), Teflon non-stick pans.',
    fact: 'Fluorine is the most chemically reactive and electronegative element of all!',
    color: '#F87171',
    shellConfig: [2, 7]
  },
  {
    id: 'chlorine',
    name: 'Chlorine',
    symbol: 'Cl',
    atomicNumber: 17,
    category: 'Halogen',
    uses: 'Disinfecting swimming pools, water treatment, bleach.',
    fact: 'Chlorine is a choking greenish-yellow gas that was used as a weapon in WWI.',
    color: '#10B981',
    shellConfig: [2, 8, 7]
  },
  {
    id: 'bromine',
    name: 'Bromine',
    symbol: 'Br',
    atomicNumber: 35,
    category: 'Halogen',
    uses: 'Flame retardants, swimming pool purifiers, photographic film.',
    fact: 'Bromine is the only non-metal element that is a liquid at room temperature!',
    color: '#EF4444',
    shellConfig: [2, 8, 18, 7]
  },
  {
    id: 'iodine',
    name: 'Iodine',
    symbol: 'I',
    atomicNumber: 53,
    category: 'Halogen',
    uses: 'Disinfectant (tincture of iodine), thyroid health supplements.',
    fact: 'Iodine vapor is a beautiful dark violet gas and stains skin brown!',
    color: '#8B5CF6',
    shellConfig: [2, 8, 18, 18, 7]
  },
  {
    id: 'astatine',
    name: 'Astatine',
    symbol: 'At',
    atomicNumber: 85,
    category: 'Halogen',
    uses: 'Cancer radiation therapy research (extremely rare).',
    fact: 'Less than one gram of astatine exists in the Earth\'s crust at any time!',
    color: '#7C3AED',
    shellConfig: [2, 8, 18, 32, 18, 7]
  },
  {
    id: 'helium',
    name: 'Helium',
    symbol: 'He',
    atomicNumber: 2,
    category: 'Noble Gas',
    uses: 'Party balloons, MRI machine cooling, scientific research.',
    fact: 'Helium is lighter than air, which is why helium-filled balloons float upwards!',
    color: '#F472B6',
    shellConfig: [2]
  },
  {
    id: 'neon',
    name: 'Neon',
    symbol: 'Ne',
    atomicNumber: 10,
    category: 'Noble Gas',
    uses: 'Glowing advertising signs, neon lamps, high-voltage indicators.',
    fact: 'Neon signs glow with a bright reddish-orange light when electrified!',
    color: '#FF4500',
    shellConfig: [2, 8]
  },
  {
    id: 'argon',
    name: 'Argon',
    symbol: 'Ar',
    atomicNumber: 18,
    category: 'Noble Gas',
    uses: 'Filling incandescent lightbulbs to preserve filament, double glazing.',
    fact: 'Argon is the third most common gas in Earth\'s atmosphere (0.93%)!',
    color: '#A78BFA',
    shellConfig: [2, 8, 8]
  },
  {
    id: 'krypton',
    name: 'Krypton',
    symbol: 'Kr',
    atomicNumber: 36,
    category: 'Noble Gas',
    uses: 'High-speed photography flashes, energy-efficient fluorescent bulbs.',
    fact: 'It is named after "kryptos", Greek for hidden, and is NOT from Superman\'s planet!',
    color: '#818CF8',
    shellConfig: [2, 8, 18, 8]
  },
  {
    id: 'xenon',
    name: 'Xenon',
    symbol: 'Xe',
    atomicNumber: 54,
    category: 'Noble Gas',
    uses: 'High-intensity projector lamps, space propulsion thrusters.',
    fact: 'Xenon flashlamps produce a bright white flash mimicking natural sunlight!',
    color: '#6366F1',
    shellConfig: [2, 8, 18, 18, 8]
  },
  {
    id: 'radon',
    name: 'Radon',
    symbol: 'Rn',
    atomicNumber: 86,
    category: 'Noble Gas',
    uses: 'Radiation therapy, earthquake prediction monitoring.',
    fact: 'Radon is a heavy, radioactive gas that can accumulate in house basements!',
    color: '#4F46E5',
    shellConfig: [2, 8, 18, 32, 18, 8]
  },
  {
    id: 'boron',
    name: 'Boron',
    symbol: 'B',
    atomicNumber: 5,
    category: 'Metalloid',
    uses: 'Borosilicate glassware (pyrex), eye drops, rocket ignition.',
    fact: 'Boron compounds are key to making strong glass that does not crack under heat!',
    color: '#FB923C',
    shellConfig: [2, 3]
  },
  {
    id: 'silicon',
    name: 'Silicon',
    symbol: 'Si',
    atomicNumber: 14,
    category: 'Metalloid',
    uses: 'Computer microchips, solar panels, glass, silicones.',
    fact: 'Silicon is a semiconductor, enabling the entire modern computer age!',
    color: '#94A3B8',
    shellConfig: [2, 8, 4]
  },
  {
    id: 'germanium',
    name: 'Germanium',
    symbol: 'Ge',
    atomicNumber: 32,
    category: 'Metalloid',
    uses: 'Infrared night-vision optics, fiber-optic communication cables.',
    fact: 'Germanium was predicted by Mendeleev before it was ever discovered!',
    color: '#64748B',
    shellConfig: [2, 8, 18, 4]
  },
  {
    id: 'arsenic',
    name: 'Arsenic',
    symbol: 'As',
    atomicNumber: 33,
    category: 'Metalloid',
    uses: 'Semiconductor doping, wood preservatives, historically as poisons.',
    fact: 'Arsenic is famous as a deadly poison in historical mystery novels!',
    color: '#F87171',
    shellConfig: [2, 8, 18, 5]
  },
  {
    id: 'antimony',
    name: 'Antimony',
    symbol: 'Sb',
    atomicNumber: 51,
    category: 'Metalloid',
    uses: 'Flame retardants, batteries, infrared detectors.',
    fact: 'Antimony was used as ancient eyeliner mascara in Egypt, called kohl!',
    color: '#FB7185',
    shellConfig: [2, 8, 18, 18, 5]
  },
  {
    id: 'tellurium',
    name: 'Tellurium',
    symbol: 'Te',
    atomicNumber: 52,
    category: 'Metalloid',
    uses: 'Solar panels, alloying element in copper and steel.',
    fact: 'Exposure to Tellurium can make your breath smell strongly like garlic!',
    color: '#F472B6',
    shellConfig: [2, 8, 18, 18, 6]
  },
  {
    id: 'polonium',
    name: 'Polonium',
    symbol: 'Po',
    atomicNumber: 84,
    category: 'Metalloid',
    uses: 'Eliminating static electricity in industrial machinery, space heating.',
    fact: 'Polonium was discovered by Marie Curie and named after her homeland, Poland!',
    color: '#E11D48',
    shellConfig: [2, 8, 18, 32, 18, 6]
  },
  {
    id: 'water',
    name: 'Water',
    symbol: 'H2O',
    atomicNumber: null,
    category: 'Compound',
    uses: 'Essential for all life, drinking, agriculture, cleaning.',
    fact: 'Water expands when it freezes, which is why ice floats on water!',
    color: '#60A5FA',
    formula: 'H₂O'
  },
  {
    id: 'co2',
    name: 'Carbon Dioxide',
    symbol: 'CO2',
    atomicNumber: null,
    category: 'Compound',
    uses: 'Fires extinguishers, soda carbonation, plant photosynthesis.',
    fact: 'Dry Ice is actually frozen solid Carbon Dioxide at -78.5°C!',
    color: '#9CA3AF',
    formula: 'CO₂'
  },
  {
    id: 'sand',
    name: 'Silicon Dioxide',
    symbol: 'SiO2',
    atomicNumber: null,
    category: 'Compound',
    uses: 'Making glass, construction concrete, filter systems.',
    fact: 'Quartz crystal and beach sand are both pure Silicon Dioxide!',
    color: '#F59E0B',
    formula: 'SiO₂'
  },
  {
    id: 'methane',
    name: 'Methane',
    symbol: 'CH4',
    atomicNumber: null,
    category: 'Compound',
    uses: 'Natural gas heating, electricity generation, chemical feedstock.',
    fact: 'Methane is a potent greenhouse gas, 25 times more trapping than CO2!',
    color: '#34D399',
    formula: 'CH₄'
  },
  {
    id: 'ammonia',
    name: 'Ammonia',
    symbol: 'NH3',
    atomicNumber: null,
    category: 'Compound',
    uses: 'Agricultural fertilizers, household glass cleaner, refrigerants.',
    fact: 'Ammonia has a very sharp, pungent smell that can wake up fainted people!',
    color: '#93C5FD',
    formula: 'NH₃'
  },
  {
    id: 'glucose',
    name: 'Glucose',
    symbol: 'C6H12O6',
    atomicNumber: null,
    category: 'Compound',
    uses: 'Primary cellular energy source in plants and animals, food sweetener.',
    fact: 'Glucose is synthesized by plants using sunlight, water, and air!',
    color: '#34D399',
    formula: 'C₆H₁₂O₆'
  },
  {
    id: 'ethanol',
    name: 'Ethanol',
    symbol: 'C2H5OH',
    atomicNumber: null,
    category: 'Compound',
    uses: 'Hand sanitizer, biofuel (gasohol), solvents, beverages.',
    fact: 'Ethanol kills bacteria by dissolving their lipid membranes and denaturing proteins!',
    color: '#818CF8',
    formula: 'C₂H₅OH'
  },
  {
    id: 'sucrose',
    name: 'Sucrose',
    symbol: 'C12H22O11',
    atomicNumber: null,
    category: 'Compound',
    uses: 'Table sugar, food sweetener, preservative.',
    fact: 'Sucrose is a double sugar (disaccharide) made of glucose and fructose!',
    color: '#F472B6',
    formula: 'C₁₂H₂₂O₁₁'
  },
  {
    id: 'plastic',
    name: 'Polyethylene (Plastic)',
    symbol: '(C2H4)n',
    atomicNumber: null,
    category: 'Polymer',
    uses: 'Shopping bags, squeeze bottles, toys, electrical insulation.',
    fact: 'It is the most common plastic in the world, with over 100 million tons made yearly!',
    color: '#FB7185',
    formula: '(C₂H₄)ₙ'
  },
  {
    id: 'pvc',
    name: 'Polyvinyl Chloride (PVC)',
    symbol: '(C2H3Cl)n',
    atomicNumber: null,
    category: 'Polymer',
    uses: 'Plumbing pipes, cable insulation, records, raincoats.',
    fact: 'PVC is the third-most widely produced synthetic plastic polymer!',
    color: '#F43F5E',
    formula: '(C₂H₃Cl)ₙ'
  },
  {
    id: 'rubber',
    name: 'Natural Rubber',
    symbol: '(C5H8)n',
    atomicNumber: null,
    category: 'Polymer',
    uses: 'Bicycle tires, erasers, elastic bands, surgical gloves.',
    fact: 'Natural rubber is harvested as a sticky, milky sap called latex from rubber trees!',
    color: '#F59E0B',
    formula: '(C₅H₈)ₙ'
  },
  {
    id: 'cellulose',
    name: 'Cellulose (Wood/Paper)',
    symbol: '(C6H10O5)n',
    atomicNumber: null,
    category: 'Polymer',
    uses: 'Writing paper, cardboard, clothing (cotton), building wood.',
    fact: 'Cellulose is the structural component of plant cell walls, and humans cannot digest it!',
    color: '#10B981',
    formula: '(C₆H₁₀O₅)ₙ'
  },
  {
    id: 'diamond',
    name: 'Diamond',
    symbol: 'C',
    atomicNumber: 6,
    category: 'Allotrope of Carbon',
    uses: 'Cutting, drilling, high-end jewelry, heatsinks.',
    fact: 'Diamond is the hardest naturally occurring substance on Earth, formed deep underground!',
    color: '#CBD5E1',
    formula: 'C'
  },
  {
    id: 'graphite',
    name: 'Graphite',
    symbol: 'C',
    atomicNumber: 6,
    category: 'Allotrope of Carbon',
    uses: 'Pencil leads, dry lubricant, batteries anodes, steel making.',
    fact: 'Unlike diamond, graphite is extremely soft and is a good conductor of electricity!',
    color: '#4B5563',
    formula: 'C'
  },
  {
    id: 'quartz',
    name: 'Quartz',
    symbol: 'SiO2',
    atomicNumber: null,
    category: 'Compound',
    uses: 'Watch oscillators, glass manufacturing, jewelry.',
    fact: 'Quartz watches work because quartz crystals generate electricity when squeezed!',
    color: '#E2E8F0',
    formula: 'SiO₂'
  },
  {
    id: 'nylon',
    name: 'Nylon',
    symbol: 'Synthetic Polymer',
    atomicNumber: null,
    category: 'Polymer',
    uses: 'Ropes, fishing nets, stockings, toothbrush bristles, parachutes.',
    fact: 'Nylon was the world\'s first fully synthetic fiber, invented in 1935!',
    color: '#818CF8',
    formula: 'Nylon'
  },
  {
    id: 'sulfuric_acid',
    name: 'Sulfuric Acid',
    symbol: 'H2SO4',
    atomicNumber: null,
    category: 'Acid',
    uses: 'Car batteries, chemical manufacturing, fertilizers, refining.',
    fact: 'A country\'s industrial strength is often measured by its sulfuric acid production!',
    color: '#EF4444',
    formula: 'H₂SO₄'
  },
  {
    id: 'hydrochloric_acid',
    name: 'Hydrochloric Acid',
    symbol: 'HCl',
    atomicNumber: null,
    category: 'Acid',
    uses: 'Stomach digestion, food processing, pickling steel, pH control.',
    fact: 'Your stomach produces hydrochloric acid to digest food and kill bacteria!',
    color: '#EF4444',
    formula: 'HCl'
  },
  {
    id: 'nitric_acid',
    name: 'Nitric Acid',
    symbol: 'HNO3',
    atomicNumber: null,
    category: 'Acid',
    uses: 'Fertilizers, explosives (TNT), rocket propellants.',
    fact: 'Nitric acid turns human skin yellow upon contact due to a reaction with proteins!',
    color: '#EF4444',
    formula: 'HNO₃'
  },
  {
    id: 'caffeine',
    name: 'Caffeine',
    symbol: 'C8H10N4O2',
    atomicNumber: null,
    category: 'Compound',
    uses: 'Stimulant in coffee/tea, alertness medicine.',
    fact: 'Caffeine acts as a natural pesticide, paralyzing and killing insects feeding on coffee plants!',
    color: '#34D399',
    formula: 'C₈H₁₀N₄O₂'
  },
  {
    id: 'teflon',
    name: 'Teflon (PTFE)',
    symbol: '(C2F4)n',
    atomicNumber: null,
    category: 'Polymer',
    uses: 'Non-stick cooking pans, waterproof clothing (Gore-Tex), seal tapes.',
    fact: 'Teflon is one of the slipperiest substances known, and even geckos can\'t stick to it!',
    color: '#64748B',
    formula: '(C₂F₄)ₙ'
  },
  {
    id: 'methane_gas',
    name: 'Carbon Monoxide',
    symbol: 'CO',
    atomicNumber: null,
    category: 'Compound',
    uses: 'Metallurgical reducing agent, fuel.',
    fact: 'Carbon monoxide is a toxic, colorless, odorless gas that binds to hemoglobin!',
    color: '#9CA3AF',
    formula: 'CO'
  },
  {
    id: 'ozone',
    name: 'Ozone',
    symbol: 'O3',
    atomicNumber: null,
    category: 'Reactive Nonmetal',
    uses: 'Water purification, deodorizing air, atmospheric UV protection.',
    fact: 'The ozone layer shields Earth from 97-99% of dangerous solar UV rays!',
    color: '#60A5FA',
    formula: 'O₃'
  },
  {
    id: 'phosphoric_acid',
    name: 'Phosphoric Acid',
    symbol: 'H3PO4',
    atomicNumber: null,
    category: 'Acid',
    uses: 'Soda flavoring (gives cola its tangy bite), rust converter.',
    fact: 'It is a weak acid but is strong enough to dissolve nails over time!',
    color: '#EF4444',
    formula: 'H₃PO₄'
  },
  {
    id: 'propane',
    name: 'Propane',
    symbol: 'C3H8',
    atomicNumber: null,
    category: 'Compound',
    uses: 'LPG gas cylinders, barbecue grills, engines fuel.',
    fact: 'Propane gas is naturally odorless; an artificial smell (mercaptan) is added for safety!',
    color: '#34D399',
    formula: 'C₃H₈'
  }
];
