import { jsPDF } from "jspdf";

export default function ReportButton({
    progress,
    status,
    waterCount,
    saltCount
}) {

    const downloadReport = () => {

        const doc = new jsPDF();

        const efficiency = (
            ((waterCount + saltCount) / 40) * 100
        ).toFixed(0);

        const temperature = (
            25 + progress * 0.08
        ).toFixed(1);

        const ph = (
            1 + (progress / 100) * 6
        ).toFixed(1);

        const now = new Date();

        doc.setFontSize(20);
        doc.text(
            "Acid-Base Neutralization Report",
            20,
            20
        );

        doc.setFontSize(12);

        doc.text(
            `Date : ${now.toLocaleDateString()}`,
            20,
            40
        );

        doc.text(
            `Time : ${now.toLocaleTimeString()}`,
            20,
            50
        );

        doc.line(20,60,190,60);

        doc.text(
            "Reaction Equation",
            20,
            75
        );

        doc.text(
            "HCl + NaOH -> NaCl + H2O",
            20,
            85
        );

        doc.line(20,95,190,95);

        doc.text(
            `Progress : ${progress}%`,
            20,
            110
        );

        doc.text(
            `Status : ${status}`,
            20,
            120
        );

        doc.text(
            `Water Produced : ${waterCount}`,
            20,
            130
        );

        doc.text(
            `Salt Produced : ${saltCount}`,
            20,
            140
        );

        doc.text(
            `Reaction Efficiency : ${efficiency}%`,
            20,
            150
        );

        doc.text(
            `Final pH : ${ph}`,
            20,
            160
        );

        doc.text(
            `Temperature : ${temperature} °C`,
            20,
            170
        );

        doc.line(20,180,190,180);

        doc.text(
            "Generated by Acid-Base Neutralization Simulator",
            20,
            195
        );

        doc.save(
            "Acid_Base_Report.pdf"
        );

    };

    return (

        <div
            style={{
                textAlign:"center",
                marginTop:"25px"
            }}
        >

            <button
                onClick={downloadReport}
                style={{
                    padding:"14px 30px",
                    background:"#0ea5e9",
                    color:"white",
                    border:"none",
                    borderRadius:"10px",
                    cursor:"pointer",
                    fontSize:"18px",
                    fontWeight:"bold"
                }}
            >
                📄 Download Report
            </button>

        </div>

    );

}
